# Sample workflow for building and deploying a Next.js site to VPS
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to VPS

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Check if Yarn is installed
        run: |
          if ! command -v yarn &> /dev/null
          then
            echo "Yarn not found, installing..."
            npm install -g yarn
          else
            echo "Yarn is already installed."
          fi

      - name: Check if PM2 is installed
        run: |
          if ! command -v pm2 &> /dev/null
          then
            echo "PM2 not found, installing..."
            npm install -g pm2
          else
            echo "PM2 is already installed."
          fi

      - name: Install dependencies
        run: yarn install

      - name: Build with Next.js
        run: yarn build

      - name: write environment variables to .env
        run: |
          touch .env
          echo "${{ secrets.leezo_env_secrets }}" >> .env

      - name: Start pm2 process
        run: pm2 startOrRestart ecosystem.config.js
